app/routes.py
# flask routes
from functools import wraps

from flask import Blueprint, render_template, url_for, flash, abort
from werkzeug.utils import redirect
from app.models import bcrypt, Comment, admin_only
from .forms import Add, Register, Login, CommentForm
from .models import Cafe, db, User, login_manager
from flask_login import login_user, login_required, logout_user, current_user

main = Blueprint("main", __name__, template_folder='app/templates')


@main.route("/")
@main.route("/home")
def home():
    cafes = db.session.query(Cafe).all()
    return render_template("index.html", cafes=cafes, current_user=current_user)

@main.route("/cafe_details/<int:cafe_id>", methods=["GET", "POST"])
def cafe_details(cafe_id):
    form = CommentForm()
    cafe = db.get_or_404(Cafe, cafe_id)
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash("You need to be logged to comment.")
            return redirect(url_for("main.login"))
        else:
            new_comment = Comment(
                content=form.comment_text.data,
                author=current_user,
                parent_cafe=cafe,
            )
            db.session.add(new_comment)
            db.session.commit()
    return render_template("cafe_details.html", cafe=cafe, current_user=current_user, form=form)

@main.route("/add", methods=["GET", "POST"])
@login_required
@admin_only
def add():
    form = Add()
    if form.validate_on_submit():
        new_cafe = Cafe(
            name = form.name.data,
            describe = form.describe.data,
            location_url = form.location_url.data,
            bg_url = form.bg_url.data,
            cafe_url = form.cafe_url.data,
            cafe = form.cafe.data,
            wifi = form.wifi.data,
            sockets = form.sockets.data,
        )
        db.session.add(new_cafe)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template("add_cafe.html", form=form, current_user=current_user)

@main.route("/delete/<int:cafe_id>")
@login_required
@admin_only
def delete(cafe_id):
    cafe = db.get_or_404(Cafe, cafe_id)
    db.session.delete(cafe)
    db.session.commit()
    return redirect(url_for('main.home'))

@main.route("/register", methods=['GET', 'POST'])
def register():
    form = Register()
    if form.validate_on_submit():
        email = form.email.data
        user =  db.session.query(User).filter_by(email=email).first()
        if not user:
            new_user = User(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                email=form.email.data,
                password=bcrypt.generate_password_hash(f"{form.password.data}").decode('utf-8'),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for('main.home'))
        else:
            flash("Wrong email. User already exist")
    return render_template("register.html", form=form, current_user=current_user)

@main.route("/login", methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        email=form.email.data
        password=form.password.data
        user = db.session.execute(db.select(User).filter_by(email=email)).scalar()
        if user:
            if bcrypt.check_password_hash(user.password, password):
                login_user(user)
                flash("Successfully logged in!")
                return redirect(url_for('main.home'))
            else:
                flash("Wrong password")
        else:
            flash("Wrong email")
    return render_template("login.html", form=form)

@main.route("/logout", methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash("Successfully logged out!")
    return redirect(url_for('main.home'))

app/templates/add_cafe.html
<!--forms to add cafe-->
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}


{% block title %} Add interesting cafe! {% endblock %}

{% block content %}
<div class ="py-5">
    <div class="text-light w-50 py-5">
        {{ render_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/base.html
<!--Base template for extending other-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css.css">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<body>

<!--Navbar-->
<header class="p-3 bg-black">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-0 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{url_for('main.home')}}" class="nav-link px-2 text-white">Home</a></li>
            {% if current_user.id == 1 %}
          <li><a href="{{url_for('main.add')}}" class="nav-link px-2 text-white">Add cafe</a></li>
            {% endif %}
        </ul>

        <div class="text-end">
            {% if not current_user.is_authenticated %}
          <a href="{{url_for('main.login')}}" type="button" class="btn btn-secondary me-2">Login</a>
          <a href="{{url_for('main.register')}}" type="button" class="btn btn-warning me-2">Sign-up</a>
            {% else %}
          <a href="{{url_for('main.logout')}}" type="button" class="btn btn-secondary me-2">Logout</a>
            {% endif %}
        </div>
      </div>
    </div>
  </header>

<!--Content block-->
{% block content %}{% endblock %}

</body>
</html>

app/templates/cafe_details.html
<!--detailed cafe-->
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}

<!--Cafe display-->
<div style="height: 50px;"></div>
<div class="container mt-5 my-5">
  <div class="p-5 text-center rounded-3 position-relative"
       style="background: url('{{ cafe.bg_url }}') center/cover no-repeat;">
    <div class="overlay"></div>
    <div class="content">
      <h1 class="text-white d-inline">{{ cafe.name }}</h1>
      <p class="lead mb-4 fw-bold">
          {{cafe.describe}}
      </p>
<p class="lead mb-4">
    <span class="me-4">Taste of cafe: {{ cafe.cafe }} </span>
    <span class="me-4">WiFi: {{ cafe.wifi }}</span>
    <span>Electricity supply: {{ cafe.sockets }}</span>
</p>
      <div class="d-inline-flex gap-5 mt-5">
        <a href="{{ cafe.location_url }}" target="_blank" class="btn btn-secondary btn-lg px-4 rounded-pill">
            Location
        </a>
         <a href="{{ cafe.cafe_url }}" target="_blank" class="btn btn-secondary btn-lg px-4 rounded-pill">
            Cafe website
        </a>
      </div>
    </div>
  </div>
</div>

<div style="padding: 0 50px 15px 50px;">
    <h2 class="text-white d-inline px-5" >Comments:</h2>
</div>

<!-- Comments Area -->
<div class="comment">
    <ul class="commentList pt-2" style="padding: 0 50px 5px 50px;">
        <!-- Show all comments -->
        {% for comment in cafe.cafe_comments: %}
        <li>
            <div class="commentText">
                <p class="text-white d-inline px-5">"{{comment.content|safe}}"
                </p><span class="sub-text text-white d-inline" style="padding-left: 60px;">Commented by: {{comment.author.first_name}} {{comment.author.last_name}}</span>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<div style="padding: 0 100px 15px 100px; color: white;">
    {{ render_form(form, novalidate=True, button_map={"submit": "secondary"}) }}
</div>




{%endblock%}

app/templates/index.html
<!--home page-->
{% extends 'base.html' %}
{% block title %} Cafes around you! {% endblock %}
{% block content %}

<!--Main background-->
<div class="px-4 pt-5 text-center border-bottom gradient-background">
    <h1 class="py-5 display-4 fw-bold text-body-emphasis">Explore Kraków's best cafes!</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4 text-body-emphasis">On this page, you'll discover the top cafes in Kraków, along with their ratings for WiFi, electricity availability, and, of course, coffee taste. ☕</p>
    </div>
    <div class="overflow-hidden" style="max-height: 45vh;">
      <div class="container px-5">
        <img src="../static/images/cafe_photo_2.jpg" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Cafe and laptop image" width="400" height="500">
      </div>
    </div>
  </div>

<!--Displaying flashed messages-->
<div class="text-light w-50 p-5">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning">
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </div>
             {% endif %}
        {% endwith %}
</div>



<!--Displaying cafes-->

{% for cafe in cafes %}
<div class="container my-5">
  <div class="p-5 text-center rounded-3 position-relative"
       style="background: url('{{ cafe.bg_url }}') center/cover no-repeat;">
    <div class="overlay"></div> <!-- Dark overlay -->
    <div class="content">
      <h1 class="text-white d-inline">{{ cafe.name }}</h1>
        {% if current_user.id == 1 %}
      <a href="{{ url_for('main.delete', cafe_id=cafe.id) }}" class="text-decoration-none ms-2">❌</a>
        {% endif %}
      <p class="lead mb-4 fw-bold">
          {{cafe.describe}}
      </p>
<p class="lead mb-4">
    <span class="me-4">Taste of cafe: {{ cafe.cafe }} </span>
    <span class="me-4">WiFi: {{ cafe.wifi }}</span>
    <span>Electricity supply: {{ cafe.sockets }}</span>
</p>
      <div class="d-inline-flex gap-2 mt-3">
        <a href="{{ url_for('main.cafe_details', cafe_id=cafe.id) }}" class="btn btn-secondary btn-lg px-4 rounded-pill">
            More info
        </a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}


{% block title %} Login {% endblock %}

{% block content %}
<div class ="py-5">
    <div class="text-light w-50 p-5">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning">
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </div>
             {% endif %}
        {% endwith %}
        {{ render_form(form, button_map={"submit": "secondary"}) }}
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}


{% block title %} Register {% endblock %}


{% block content %}
<div class ="py-5">
    <div class="text-light w-50 p-5">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning">
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </div>
             {% endif %}
        {% endwith %}
        {{ render_form(form, button_map={"submit": "secondary"}) }}
    </div>
</div>
{% endblock %}